name: Build YANBF Release

on:
  release:
    types: [published]

jobs:
  generator:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build standard
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get tools
        run: |
          wget "https://github.com/ihaveamac/ctr_toolkit/releases/download/make_cia6.4builds/make_cia6.4builds.zip"
          unzip make_cia6.4builds.zip
          sudo cp linux/make_cia /usr/local/bin/make_cia && sudo chmod +x /usr/local/bin/make_cia
      - name: Make YANBF
        run: |
          make dist
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: dist
          name: YANBF

  windows:
    runs-on: windows-2019
    name: Build Windows
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: generator
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: YANBF
          path: YANBF
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install -r YANBF/generator/requirements.txt
          python -m pip install cx_Logging
          python -m pip install cx-Freeze
      - name: Create package
        run: |
          curl -LJO "https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool.zip"
          unzip 3dstool.zip
          mv -f 3dstool.exe ext_key.txt ignore_3dstool.txt YANBF/generator
          curl -LJO "https://github.com/YANBForwarder/tex3ds/releases/download/v2.3.0/tex3ds.exe"
          mv -f tex3ds.exe YANBF/generator/tex3ds.exe
          curl -LJO "https://github.com/Epicpkmn11/bannertool/releases/latest/download/bannertool.zip"
          unzip bannertool.zip
          mv -f windows-x86_64/bannertool.exe YANBF/generator/bannertool.exe
          curl -LJO "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-win_x86_64.zip"
          unzip makerom-v0.18-win_x86_64.zip
          mv -f makerom.exe YANBF/generator/makerom.exe
          curl -LJO "https://github.com/YANBForwarder/GUI/releases/latest/download/YANBF-GUI.exe"
          mv -f YANBF-GUI.exe YANBF/generator/YANBF-GUI.exe
          cd YANBF/generator
          python setup.py build
          cp -r dist/* .
          rm -rf *.py dist __pycache__ dist requirements.txt
        shell: bash
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: YANBF
          name: YANBF-Windows

  macos:
    runs-on: macos-10.15
    name: Build macOS
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: generator
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: YANBF
          path: YANBF
      - name: Install dependencies
        run: |
          python3 -m pip install -r YANBF/generator/requirements.txt
          python3 -m pip install pyinstaller
      - name: Create package
        run: |
          wget https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool_macos_x86_64.tar.gz
          tar xvzf 3dstool_macos_x86_64.tar.gz
          mv -f 3dstool ext_key.txt ignore_3dstool.txt YANBF/generator
          wget https://github.com/YANBForwarder/tex3ds/releases/download/v2.3.0/tex3ds-macos-universal
          mv -f tex3ds-macos-universal YANBF/generator/tex3ds
          wget "https://github.com/Epicpkmn11/bannertool/releases/latest/download/bannertool.zip"
          unzip bannertool.zip
          mv -f mac-x86_64/bannertool YANBF/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-macos_x86_64.zip"
          unzip makerom-v0.18-macos_x86_64.zip
          mv -f makerom YANBF/generator/makerom
          wget "https://github.com/YANBForwarder/GUI/releases/latest/download/YANBF-GUI.dmg"
          mv -f YANBF-GUI.dmg YANBF/generator/YANBF-GUI.dmg
          cd YANBF/generator
          pyinstaller --onefile generator.py
          mv dist/generator generator
          rm -rf *.py build generator.spec __pycache__ dist requirements.txt
      - name: chmod packages, and double zip because screw GitHub
        run: |
          chmod +x YANBF/generator/generator YANBF/generator/makerom YANBF/generator/bannertool YANBF/generator/tex3ds YANBF/generator/3dstool
          mkdir actions
          cd YANBF
          zip -r ../actions/YANBF-macOS.zip *
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: actions
          name: YANBF-macOS

  linux:
    runs-on: ubuntu-20.04
    name: Build Linux
    container: devkitpro/devkitarm
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: generator
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: YANBF
          path: YANBF
      - name: Install dependencies
        run: |
          pip3 install -r YANBF/generator/requirements.txt
          pip3 install pyinstaller
      - name: Create package
        run: |
          sudo cp /opt/devkitpro/tools/bin/tex3ds YANBF/generator/tex3ds
          wget https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool_linux_x86_64.tar.gz
          tar xvzf 3dstool_linux_x86_64.tar.gz
          mv -f 3dstool ext_key.txt ignore_3dstool.txt YANBF/generator
          wget "https://github.com/Epicpkmn11/bannertool/releases/latest/download/bannertool.zip"
          unzip bannertool.zip
          mv -f linux-x86_64/bannertool YANBF/generator/bannertool
          wget "https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-ubuntu_x86_64.zip"
          unzip makerom-v0.18-ubuntu_x86_64.zip
          mv -f makerom YANBF/generator/makerom
          wget "https://github.com/YANBForwarder/GUI/releases/latest/download/YANBF-GUI.AppImage"
          mv -f YANBF-GUI.AppImage YANBF/generator/YANBF-GUI.AppImage
          cd YANBF/generator
          pyinstaller --onefile generator.py
          mv dist/generator generator
          rm -rf *.py build generator.spec __pycache__ dist requirements.txt
      - name: chmod packages, and double zip because screw GitHub
        run: |
          chmod +x YANBF/generator/generator YANBF/generator/makerom YANBF/generator/bannertool YANBF/generator/tex3ds YANBF/generator/3dstool
          mkdir actions
          cd YANBF
          zip -r ../actions/YANBF-Linux.zip *
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: actions
          name: YANBF-Linux

  release:
    runs-on: ubuntu-latest
    name: Release
    if: ${{ success() }}
    needs: [macos, windows, linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Re-zip everything because this isn't implemented for whatever reason
        run: |
          cd YANBF-Windows
          zip -r ../YANBF-Windows.zip *
          cd ../YANBF-macOS
          zip -r ../YANBF-macOS.zip *
          cd ../YANBF-Linux
          zip -r ../YANBF-Linux.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            YANBF-Windows/bootstrap.cia
            YANBF-Windows.zip
            YANBF-macOS.zip
            YANBF-Linux.zip
